name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      appName:
        required: true
        type: string
      terraformPathFolder:
        required: true
        type: string

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraformPathFolder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.environment }}-tfplan
          path: ${{ inputs.terraformPathFolder }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Terraform Apply
        run: terraform apply -auto-approve ${{ inputs.environment }}-tfplan

      - name: Show Terraform State
        run: terraform show