name: Terraform Plan

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      appName:
        required: true
        type: string
      terraformPathFolder:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraformPathFolder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=${{ inputs.environment }}-tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}-tfplan
          path: ${{ inputs.terraformPathFolder }}/${{ inputs.environment }}-tfplan