name: Deploy Docker Container App

on:
  push:
    paths:
      - '.github/workflows/deploy-docker.yaml'
      - 'XXXX/**' # Replace 'XXXX' with the actual path to your Dockerfile or application code
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy-docker: 
    uses: xpandit/devops/.github/workflows/docker-flow.yml@main
    with:
      vmImageName: 'ubuntu-latest'
      resourceGroupName: 'XXXX'
      containerRegistry: 'XXXX.azurecr.io'
      containerAppName: 'XXXX'
      dockerfilePath: './Dockerfile'
      imageRepository: 'XXXX'
      tag: ${{ github.run_id }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}