name: Bicep Deploy Template

on:
  workflow_call:
    inputs:
      resource-group:
        required: true
        type: string
      bicep-file:
        required: true
        type: string
      location:
        required: true
        type: string
      parameter-file:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep
        run: |
          az deployment group create \
            --resource-group ${{ inputs.resource-group }} \
            --template-file ${{ inputs.bicep-file }} \
            --parameters ${{ inputs.parameter-file }} \
            --parameters location=${{ inputs.location }}