name: Bicep Deploy Template

on:
  workflow_call:
    inputs:
      resource-group:
        required: true
        type: string
      bicep-file:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Resource Group
        run: |
          az group create --name ${{ inputs.resource-group }} --location northeurope

      - name: Deploy Bicep
        run: |
          az deployment group create \
            --resource-group ${{ inputs.resource-group }} \
            --template-file ${{ inputs.bicep-file }}