name: Deploy Docker Image

on:
  workflow_call:
    inputs:
      vmImageName:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      containerAppName:
        required: true
        type: string
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      containerRegistry:
        required: true
        type: string
      imageRepository:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy_docker:
    runs-on: ${{ inputs.vmImageName }}
    steps:
      - uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Azure Container Registry Login
      - name: Azure Container Registry Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ inputs.containerRegistry }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ inputs.containerAppName }} \
            --resource-group ${{ inputs.resourceGroupName }} \
            --image ${{ inputs.containerRegistry }}/${{ inputs.imageRepository }}:${{ inputs.tag }}
