name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

  wait_for_validation:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Manual Validation
        uses: hmarr/validate-action@v1
        with:
          message: 'Please validate the Terraform plan and approve to continue.'

  apply:
    runs-on: ubuntu-latest
    needs: wait_for_validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: .

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Apply
        run: terraform apply tfplan